### ISSUE TITLE
Unable to download some datasets

### ISSUE THREAD

**Issue by arthur0219** [icbcbicc/IQA-Dataset#2]
Firstly, thanks a lot for this great work of yours.
Unfortunately, some datasets cannot be downloaded through the links given in readme.md. 
Could you please give me some new links to download some of those datasets, including A57, MDID2013, MDID2016, Toyama, PDAP-HDDS. Is it possible for you to upload these datasets to Baidudisk? 
Thank you very much.

**Comment by arthur0219** [comment]
By the way, do you have the passwords for SDIVL and MDIVL?

**Comment by icbcbicc** [comment]
Hi,

I tested the links and they appear to be working. Can you describe the error you're receiving? 

The script should be able to download and unzip SDIVL and MDIVL without a password.

**Comment by arthur0219** [comment]
Hi,

Thanks for your reply!

PDAP-HDDS is a large-scale database that I need, but the link(https://sites.google.com/site/eelab907/zi-liao-ku) seems not working, the error on the Google Drive website is "Sorry, the file you have requested does not exist."

**Comment by icbcbicc** [comment]
This repo supports PDAP-HDDS. You can try this:
```
from load_dataset import load_dataset
dataset = load_dataset("PDAP-HDDS")
```

**Comment by arthur0219** [comment]
Thank you very much!

**Comment by icbcbicc** [comment]
The links provided in the readme are official links to the datasets and not download links. Please refer to [demo.py](https://github.com/icbcbicc/IQA-Dataset/blob/master/demo.py) for instructions on how to use this script.

**Comment by arthur0219** [comment]
Thanks a lot, great help!
