### ISSUE TITLE
Csiq should be dmos

### ISSUE THREAD

**Issue by tuvovan** [icbcbicc/IQA-Dataset#3]
Hi 

I found that there is a wrong information about csiq database. According to the official website here https://s2.smu.edu/~eclarson/csiq.html, the score should be in DMOS form.

**Comment by icbcbicc** [comment]
Thanks, fixed in 0424216fb2205908438bd25b2a0a82f026c08a5e.

**Comment by tuvovan** [comment]
Kadid10k is also DMOS...

**Comment by icbcbicc** [comment]
> Kadid10k is also DMOS...

KADID10K is actually using MOS. On the official [website](https://database.mmsp-kn.de/kadid-10k-database.html) it says 

> The range of DMOS is [1 5], high value of DMOS corresponds to higher visual quality of image. ​
