### ISSUE TITLE
UHD-IQA dataset

### ISSUE THREAD

**Issue by LorenzoAgnolucci** [icbcbicc/IQA-Dataset#5]
Hi,

Could you please add the UHD-IQA dataset  ([paper](https://arxiv.org/abs/2406.17472), [download](https://database.mmsp-kn.de/uhd-iqa-benchmark-database.html))? It's a No-Reference IQA dataset composed of high-resolution images annotated with MOS.

**Comment by icbcbicc** [comment]
We have included it. Thank you for your suggestion.

**Comment by LorenzoAgnolucci** [comment]
Thank you very much!
